/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangPublicRouteRouteImport } from './routes/$lang/_public/route'
import { Route as LangAuthenticatedRouteRouteImport } from './routes/$lang/_authenticated/route'
import { Route as LangAuthenticatedAccessDeniedRouteImport } from './routes/$lang/_authenticated/access-denied'
import { Route as LangPublicGuestRouteRouteImport } from './routes/$lang/_public/_guest/route'
import { Route as LangAuthenticatedWorkspacesRouteRouteImport } from './routes/$lang/_authenticated/workspaces/route'
import { Route as LangAuthenticatedAppRouteRouteImport } from './routes/$lang/_authenticated/_app/route'
import { Route as LangAuthenticatedWorkspacesIndexRouteImport } from './routes/$lang/_authenticated/workspaces/index'
import { Route as LangAuthenticatedOrganizationsIndexRouteImport } from './routes/$lang/_authenticated/organizations/index'
import { Route as LangPublicVerifyEmailTokenRouteImport } from './routes/$lang/_public/verify-email/$token'
import { Route as LangPublicInviteTokenRouteImport } from './routes/$lang/_public/invite/$token'
import { Route as LangPublicGuestSignUpRouteImport } from './routes/$lang/_public/_guest/sign-up'
import { Route as LangPublicGuestSignInRouteImport } from './routes/$lang/_public/_guest/sign-in'
import { Route as LangAuthenticatedWorkspacesNewRouteImport } from './routes/$lang/_authenticated/workspaces/new'
import { Route as LangAuthenticatedWorkspaceWorkspaceIdRouteImport } from './routes/$lang/_authenticated/workspace/$workspaceId'
import { Route as LangAuthenticatedOrganizationsNewRouteImport } from './routes/$lang/_authenticated/organizations/new'
import { Route as LangAuthenticatedOrganizationsOrganizationIdRouteImport } from './routes/$lang/_authenticated/organizations/$organizationId'
import { Route as LangAuthenticatedAppScheduleRouteImport } from './routes/$lang/_authenticated/_app/schedule'
import { Route as LangAuthenticatedAppMyChatRouteImport } from './routes/$lang/_authenticated/_app/my-chat'
import { Route as LangAuthenticatedAppColaborandoRouteImport } from './routes/$lang/_authenticated/_app/colaborando'
import { Route as LangAuthenticatedWorkspacesWorkspaceIdRouteRouteImport } from './routes/$lang/_authenticated/workspaces/$workspaceId/route'
import { Route as LangAuthenticatedAppPagePageIdRouteImport } from './routes/$lang/_authenticated/_app/page/$pageId'
import { Route as LangAuthenticatedWorkspacesWorkspaceIdSettingsRouteRouteImport } from './routes/$lang/_authenticated/workspaces/$workspaceId/settings/route'
import { Route as LangAuthenticatedAccessScopeScopeIdRouteRouteImport } from './routes/$lang/_authenticated/access/$scope/$scopeId/route'
import { Route as LangAuthenticatedWorkspacesWorkspaceIdSettingsIndexRouteImport } from './routes/$lang/_authenticated/workspaces/$workspaceId/settings/index'
import { Route as LangAuthenticatedAccessScopeScopeIdIndexRouteImport } from './routes/$lang/_authenticated/access/$scope/$scopeId/index'
import { Route as LangAuthenticatedWorkspacesWorkspaceIdSettingsMembersRouteImport } from './routes/$lang/_authenticated/workspaces/$workspaceId/settings/members'
import { Route as LangAuthenticatedWorkspacesWorkspaceIdSettingsGeneralRouteImport } from './routes/$lang/_authenticated/workspaces/$workspaceId/settings/general'
import { Route as LangAuthenticatedAccessScopeScopeIdRolesRouteImport } from './routes/$lang/_authenticated/access/$scope/$scopeId/roles'
import { Route as LangAuthenticatedAccessScopeScopeIdRequestsIndexRouteImport } from './routes/$lang/_authenticated/access/$scope/$scopeId/requests/index'
import { Route as LangAuthenticatedAccessScopeScopeIdRequestsRequestIdRouteImport } from './routes/$lang/_authenticated/access/$scope/$scopeId/requests/$requestId'
import { Route as LangAuthenticatedAccessScopeScopeIdMemberMemberIdRouteImport } from './routes/$lang/_authenticated/access/$scope/$scopeId/member/$memberId'

const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPublicRouteRoute = LangPublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAuthenticatedRouteRoute = LangAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAuthenticatedAccessDeniedRoute =
  LangAuthenticatedAccessDeniedRouteImport.update({
    id: '/access-denied',
    path: '/access-denied',
    getParentRoute: () => LangAuthenticatedRouteRoute,
  } as any)
const LangPublicGuestRouteRoute = LangPublicGuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => LangPublicRouteRoute,
} as any)
const LangAuthenticatedWorkspacesRouteRoute =
  LangAuthenticatedWorkspacesRouteRouteImport.update({
    id: '/workspaces',
    path: '/workspaces',
    getParentRoute: () => LangAuthenticatedRouteRoute,
  } as any)
const LangAuthenticatedAppRouteRoute =
  LangAuthenticatedAppRouteRouteImport.update({
    id: '/_app',
    getParentRoute: () => LangAuthenticatedRouteRoute,
  } as any)
const LangAuthenticatedWorkspacesIndexRoute =
  LangAuthenticatedWorkspacesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangAuthenticatedWorkspacesRouteRoute,
  } as any)
const LangAuthenticatedOrganizationsIndexRoute =
  LangAuthenticatedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => LangAuthenticatedRouteRoute,
  } as any)
const LangPublicVerifyEmailTokenRoute =
  LangPublicVerifyEmailTokenRouteImport.update({
    id: '/verify-email/$token',
    path: '/verify-email/$token',
    getParentRoute: () => LangPublicRouteRoute,
  } as any)
const LangPublicInviteTokenRoute = LangPublicInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => LangPublicRouteRoute,
} as any)
const LangPublicGuestSignUpRoute = LangPublicGuestSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => LangPublicGuestRouteRoute,
} as any)
const LangPublicGuestSignInRoute = LangPublicGuestSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => LangPublicGuestRouteRoute,
} as any)
const LangAuthenticatedWorkspacesNewRoute =
  LangAuthenticatedWorkspacesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => LangAuthenticatedWorkspacesRouteRoute,
  } as any)
const LangAuthenticatedWorkspaceWorkspaceIdRoute =
  LangAuthenticatedWorkspaceWorkspaceIdRouteImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => LangAuthenticatedRouteRoute,
  } as any)
const LangAuthenticatedOrganizationsNewRoute =
  LangAuthenticatedOrganizationsNewRouteImport.update({
    id: '/organizations/new',
    path: '/organizations/new',
    getParentRoute: () => LangAuthenticatedRouteRoute,
  } as any)
const LangAuthenticatedOrganizationsOrganizationIdRoute =
  LangAuthenticatedOrganizationsOrganizationIdRouteImport.update({
    id: '/organizations/$organizationId',
    path: '/organizations/$organizationId',
    getParentRoute: () => LangAuthenticatedRouteRoute,
  } as any)
const LangAuthenticatedAppScheduleRoute =
  LangAuthenticatedAppScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => LangAuthenticatedAppRouteRoute,
  } as any)
const LangAuthenticatedAppMyChatRoute =
  LangAuthenticatedAppMyChatRouteImport.update({
    id: '/my-chat',
    path: '/my-chat',
    getParentRoute: () => LangAuthenticatedAppRouteRoute,
  } as any)
const LangAuthenticatedAppColaborandoRoute =
  LangAuthenticatedAppColaborandoRouteImport.update({
    id: '/colaborando',
    path: '/colaborando',
    getParentRoute: () => LangAuthenticatedAppRouteRoute,
  } as any)
const LangAuthenticatedWorkspacesWorkspaceIdRouteRoute =
  LangAuthenticatedWorkspacesWorkspaceIdRouteRouteImport.update({
    id: '/$workspaceId',
    path: '/$workspaceId',
    getParentRoute: () => LangAuthenticatedWorkspacesRouteRoute,
  } as any)
const LangAuthenticatedAppPagePageIdRoute =
  LangAuthenticatedAppPagePageIdRouteImport.update({
    id: '/page/$pageId',
    path: '/page/$pageId',
    getParentRoute: () => LangAuthenticatedAppRouteRoute,
  } as any)
const LangAuthenticatedWorkspacesWorkspaceIdSettingsRouteRoute =
  LangAuthenticatedWorkspacesWorkspaceIdSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LangAuthenticatedWorkspacesWorkspaceIdRouteRoute,
  } as any)
const LangAuthenticatedAccessScopeScopeIdRouteRoute =
  LangAuthenticatedAccessScopeScopeIdRouteRouteImport.update({
    id: '/access/$scope/$scopeId',
    path: '/access/$scope/$scopeId',
    getParentRoute: () => LangAuthenticatedRouteRoute,
  } as any)
const LangAuthenticatedWorkspacesWorkspaceIdSettingsIndexRoute =
  LangAuthenticatedWorkspacesWorkspaceIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      LangAuthenticatedWorkspacesWorkspaceIdSettingsRouteRoute,
  } as any)
const LangAuthenticatedAccessScopeScopeIdIndexRoute =
  LangAuthenticatedAccessScopeScopeIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangAuthenticatedAccessScopeScopeIdRouteRoute,
  } as any)
const LangAuthenticatedWorkspacesWorkspaceIdSettingsMembersRoute =
  LangAuthenticatedWorkspacesWorkspaceIdSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () =>
      LangAuthenticatedWorkspacesWorkspaceIdSettingsRouteRoute,
  } as any)
const LangAuthenticatedWorkspacesWorkspaceIdSettingsGeneralRoute =
  LangAuthenticatedWorkspacesWorkspaceIdSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () =>
      LangAuthenticatedWorkspacesWorkspaceIdSettingsRouteRoute,
  } as any)
const LangAuthenticatedAccessScopeScopeIdRolesRoute =
  LangAuthenticatedAccessScopeScopeIdRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => LangAuthenticatedAccessScopeScopeIdRouteRoute,
  } as any)
const LangAuthenticatedAccessScopeScopeIdRequestsIndexRoute =
  LangAuthenticatedAccessScopeScopeIdRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => LangAuthenticatedAccessScopeScopeIdRouteRoute,
  } as any)
const LangAuthenticatedAccessScopeScopeIdRequestsRequestIdRoute =
  LangAuthenticatedAccessScopeScopeIdRequestsRequestIdRouteImport.update({
    id: '/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => LangAuthenticatedAccessScopeScopeIdRouteRoute,
  } as any)
const LangAuthenticatedAccessScopeScopeIdMemberMemberIdRoute =
  LangAuthenticatedAccessScopeScopeIdMemberMemberIdRouteImport.update({
    id: '/member/$memberId',
    path: '/member/$memberId',
    getParentRoute: () => LangAuthenticatedAccessScopeScopeIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/workspaces': typeof LangAuthenticatedWorkspacesRouteRouteWithChildren
  '/$lang/access-denied': typeof LangAuthenticatedAccessDeniedRoute
  '/$lang/workspaces/$workspaceId': typeof LangAuthenticatedWorkspacesWorkspaceIdRouteRouteWithChildren
  '/$lang/colaborando': typeof LangAuthenticatedAppColaborandoRoute
  '/$lang/my-chat': typeof LangAuthenticatedAppMyChatRoute
  '/$lang/schedule': typeof LangAuthenticatedAppScheduleRoute
  '/$lang/organizations/$organizationId': typeof LangAuthenticatedOrganizationsOrganizationIdRoute
  '/$lang/organizations/new': typeof LangAuthenticatedOrganizationsNewRoute
  '/$lang/workspace/$workspaceId': typeof LangAuthenticatedWorkspaceWorkspaceIdRoute
  '/$lang/workspaces/new': typeof LangAuthenticatedWorkspacesNewRoute
  '/$lang/sign-in': typeof LangPublicGuestSignInRoute
  '/$lang/sign-up': typeof LangPublicGuestSignUpRoute
  '/$lang/invite/$token': typeof LangPublicInviteTokenRoute
  '/$lang/verify-email/$token': typeof LangPublicVerifyEmailTokenRoute
  '/$lang/organizations/': typeof LangAuthenticatedOrganizationsIndexRoute
  '/$lang/workspaces/': typeof LangAuthenticatedWorkspacesIndexRoute
  '/$lang/access/$scope/$scopeId': typeof LangAuthenticatedAccessScopeScopeIdRouteRouteWithChildren
  '/$lang/workspaces/$workspaceId/settings': typeof LangAuthenticatedWorkspacesWorkspaceIdSettingsRouteRouteWithChildren
  '/$lang/page/$pageId': typeof LangAuthenticatedAppPagePageIdRoute
  '/$lang/access/$scope/$scopeId/roles': typeof LangAuthenticatedAccessScopeScopeIdRolesRoute
  '/$lang/workspaces/$workspaceId/settings/general': typeof LangAuthenticatedWorkspacesWorkspaceIdSettingsGeneralRoute
  '/$lang/workspaces/$workspaceId/settings/members': typeof LangAuthenticatedWorkspacesWorkspaceIdSettingsMembersRoute
  '/$lang/access/$scope/$scopeId/': typeof LangAuthenticatedAccessScopeScopeIdIndexRoute
  '/$lang/workspaces/$workspaceId/settings/': typeof LangAuthenticatedWorkspacesWorkspaceIdSettingsIndexRoute
  '/$lang/access/$scope/$scopeId/member/$memberId': typeof LangAuthenticatedAccessScopeScopeIdMemberMemberIdRoute
  '/$lang/access/$scope/$scopeId/requests/$requestId': typeof LangAuthenticatedAccessScopeScopeIdRequestsRequestIdRoute
  '/$lang/access/$scope/$scopeId/requests/': typeof LangAuthenticatedAccessScopeScopeIdRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/access-denied': typeof LangAuthenticatedAccessDeniedRoute
  '/$lang/workspaces/$workspaceId': typeof LangAuthenticatedWorkspacesWorkspaceIdRouteRouteWithChildren
  '/$lang/colaborando': typeof LangAuthenticatedAppColaborandoRoute
  '/$lang/my-chat': typeof LangAuthenticatedAppMyChatRoute
  '/$lang/schedule': typeof LangAuthenticatedAppScheduleRoute
  '/$lang/organizations/$organizationId': typeof LangAuthenticatedOrganizationsOrganizationIdRoute
  '/$lang/organizations/new': typeof LangAuthenticatedOrganizationsNewRoute
  '/$lang/workspace/$workspaceId': typeof LangAuthenticatedWorkspaceWorkspaceIdRoute
  '/$lang/workspaces/new': typeof LangAuthenticatedWorkspacesNewRoute
  '/$lang/sign-in': typeof LangPublicGuestSignInRoute
  '/$lang/sign-up': typeof LangPublicGuestSignUpRoute
  '/$lang/invite/$token': typeof LangPublicInviteTokenRoute
  '/$lang/verify-email/$token': typeof LangPublicVerifyEmailTokenRoute
  '/$lang/organizations': typeof LangAuthenticatedOrganizationsIndexRoute
  '/$lang/workspaces': typeof LangAuthenticatedWorkspacesIndexRoute
  '/$lang/page/$pageId': typeof LangAuthenticatedAppPagePageIdRoute
  '/$lang/access/$scope/$scopeId/roles': typeof LangAuthenticatedAccessScopeScopeIdRolesRoute
  '/$lang/workspaces/$workspaceId/settings/general': typeof LangAuthenticatedWorkspacesWorkspaceIdSettingsGeneralRoute
  '/$lang/workspaces/$workspaceId/settings/members': typeof LangAuthenticatedWorkspacesWorkspaceIdSettingsMembersRoute
  '/$lang/access/$scope/$scopeId': typeof LangAuthenticatedAccessScopeScopeIdIndexRoute
  '/$lang/workspaces/$workspaceId/settings': typeof LangAuthenticatedWorkspacesWorkspaceIdSettingsIndexRoute
  '/$lang/access/$scope/$scopeId/member/$memberId': typeof LangAuthenticatedAccessScopeScopeIdMemberMemberIdRoute
  '/$lang/access/$scope/$scopeId/requests/$requestId': typeof LangAuthenticatedAccessScopeScopeIdRequestsRequestIdRoute
  '/$lang/access/$scope/$scopeId/requests': typeof LangAuthenticatedAccessScopeScopeIdRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/_authenticated': typeof LangAuthenticatedRouteRouteWithChildren
  '/$lang/_public': typeof LangPublicRouteRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/_authenticated/_app': typeof LangAuthenticatedAppRouteRouteWithChildren
  '/$lang/_authenticated/workspaces': typeof LangAuthenticatedWorkspacesRouteRouteWithChildren
  '/$lang/_public/_guest': typeof LangPublicGuestRouteRouteWithChildren
  '/$lang/_authenticated/access-denied': typeof LangAuthenticatedAccessDeniedRoute
  '/$lang/_authenticated/workspaces/$workspaceId': typeof LangAuthenticatedWorkspacesWorkspaceIdRouteRouteWithChildren
  '/$lang/_authenticated/_app/colaborando': typeof LangAuthenticatedAppColaborandoRoute
  '/$lang/_authenticated/_app/my-chat': typeof LangAuthenticatedAppMyChatRoute
  '/$lang/_authenticated/_app/schedule': typeof LangAuthenticatedAppScheduleRoute
  '/$lang/_authenticated/organizations/$organizationId': typeof LangAuthenticatedOrganizationsOrganizationIdRoute
  '/$lang/_authenticated/organizations/new': typeof LangAuthenticatedOrganizationsNewRoute
  '/$lang/_authenticated/workspace/$workspaceId': typeof LangAuthenticatedWorkspaceWorkspaceIdRoute
  '/$lang/_authenticated/workspaces/new': typeof LangAuthenticatedWorkspacesNewRoute
  '/$lang/_public/_guest/sign-in': typeof LangPublicGuestSignInRoute
  '/$lang/_public/_guest/sign-up': typeof LangPublicGuestSignUpRoute
  '/$lang/_public/invite/$token': typeof LangPublicInviteTokenRoute
  '/$lang/_public/verify-email/$token': typeof LangPublicVerifyEmailTokenRoute
  '/$lang/_authenticated/organizations/': typeof LangAuthenticatedOrganizationsIndexRoute
  '/$lang/_authenticated/workspaces/': typeof LangAuthenticatedWorkspacesIndexRoute
  '/$lang/_authenticated/access/$scope/$scopeId': typeof LangAuthenticatedAccessScopeScopeIdRouteRouteWithChildren
  '/$lang/_authenticated/workspaces/$workspaceId/settings': typeof LangAuthenticatedWorkspacesWorkspaceIdSettingsRouteRouteWithChildren
  '/$lang/_authenticated/_app/page/$pageId': typeof LangAuthenticatedAppPagePageIdRoute
  '/$lang/_authenticated/access/$scope/$scopeId/roles': typeof LangAuthenticatedAccessScopeScopeIdRolesRoute
  '/$lang/_authenticated/workspaces/$workspaceId/settings/general': typeof LangAuthenticatedWorkspacesWorkspaceIdSettingsGeneralRoute
  '/$lang/_authenticated/workspaces/$workspaceId/settings/members': typeof LangAuthenticatedWorkspacesWorkspaceIdSettingsMembersRoute
  '/$lang/_authenticated/access/$scope/$scopeId/': typeof LangAuthenticatedAccessScopeScopeIdIndexRoute
  '/$lang/_authenticated/workspaces/$workspaceId/settings/': typeof LangAuthenticatedWorkspacesWorkspaceIdSettingsIndexRoute
  '/$lang/_authenticated/access/$scope/$scopeId/member/$memberId': typeof LangAuthenticatedAccessScopeScopeIdMemberMemberIdRoute
  '/$lang/_authenticated/access/$scope/$scopeId/requests/$requestId': typeof LangAuthenticatedAccessScopeScopeIdRequestsRequestIdRoute
  '/$lang/_authenticated/access/$scope/$scopeId/requests/': typeof LangAuthenticatedAccessScopeScopeIdRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/'
    | '/$lang/workspaces'
    | '/$lang/access-denied'
    | '/$lang/workspaces/$workspaceId'
    | '/$lang/colaborando'
    | '/$lang/my-chat'
    | '/$lang/schedule'
    | '/$lang/organizations/$organizationId'
    | '/$lang/organizations/new'
    | '/$lang/workspace/$workspaceId'
    | '/$lang/workspaces/new'
    | '/$lang/sign-in'
    | '/$lang/sign-up'
    | '/$lang/invite/$token'
    | '/$lang/verify-email/$token'
    | '/$lang/organizations/'
    | '/$lang/workspaces/'
    | '/$lang/access/$scope/$scopeId'
    | '/$lang/workspaces/$workspaceId/settings'
    | '/$lang/page/$pageId'
    | '/$lang/access/$scope/$scopeId/roles'
    | '/$lang/workspaces/$workspaceId/settings/general'
    | '/$lang/workspaces/$workspaceId/settings/members'
    | '/$lang/access/$scope/$scopeId/'
    | '/$lang/workspaces/$workspaceId/settings/'
    | '/$lang/access/$scope/$scopeId/member/$memberId'
    | '/$lang/access/$scope/$scopeId/requests/$requestId'
    | '/$lang/access/$scope/$scopeId/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/$lang/access-denied'
    | '/$lang/workspaces/$workspaceId'
    | '/$lang/colaborando'
    | '/$lang/my-chat'
    | '/$lang/schedule'
    | '/$lang/organizations/$organizationId'
    | '/$lang/organizations/new'
    | '/$lang/workspace/$workspaceId'
    | '/$lang/workspaces/new'
    | '/$lang/sign-in'
    | '/$lang/sign-up'
    | '/$lang/invite/$token'
    | '/$lang/verify-email/$token'
    | '/$lang/organizations'
    | '/$lang/workspaces'
    | '/$lang/page/$pageId'
    | '/$lang/access/$scope/$scopeId/roles'
    | '/$lang/workspaces/$workspaceId/settings/general'
    | '/$lang/workspaces/$workspaceId/settings/members'
    | '/$lang/access/$scope/$scopeId'
    | '/$lang/workspaces/$workspaceId/settings'
    | '/$lang/access/$scope/$scopeId/member/$memberId'
    | '/$lang/access/$scope/$scopeId/requests/$requestId'
    | '/$lang/access/$scope/$scopeId/requests'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/_authenticated'
    | '/$lang/_public'
    | '/$lang/'
    | '/$lang/_authenticated/_app'
    | '/$lang/_authenticated/workspaces'
    | '/$lang/_public/_guest'
    | '/$lang/_authenticated/access-denied'
    | '/$lang/_authenticated/workspaces/$workspaceId'
    | '/$lang/_authenticated/_app/colaborando'
    | '/$lang/_authenticated/_app/my-chat'
    | '/$lang/_authenticated/_app/schedule'
    | '/$lang/_authenticated/organizations/$organizationId'
    | '/$lang/_authenticated/organizations/new'
    | '/$lang/_authenticated/workspace/$workspaceId'
    | '/$lang/_authenticated/workspaces/new'
    | '/$lang/_public/_guest/sign-in'
    | '/$lang/_public/_guest/sign-up'
    | '/$lang/_public/invite/$token'
    | '/$lang/_public/verify-email/$token'
    | '/$lang/_authenticated/organizations/'
    | '/$lang/_authenticated/workspaces/'
    | '/$lang/_authenticated/access/$scope/$scopeId'
    | '/$lang/_authenticated/workspaces/$workspaceId/settings'
    | '/$lang/_authenticated/_app/page/$pageId'
    | '/$lang/_authenticated/access/$scope/$scopeId/roles'
    | '/$lang/_authenticated/workspaces/$workspaceId/settings/general'
    | '/$lang/_authenticated/workspaces/$workspaceId/settings/members'
    | '/$lang/_authenticated/access/$scope/$scopeId/'
    | '/$lang/_authenticated/workspaces/$workspaceId/settings/'
    | '/$lang/_authenticated/access/$scope/$scopeId/member/$memberId'
    | '/$lang/_authenticated/access/$scope/$scopeId/requests/$requestId'
    | '/$lang/_authenticated/access/$scope/$scopeId/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/_public': {
      id: '/$lang/_public'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangPublicRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/_authenticated': {
      id: '/$lang/_authenticated'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangAuthenticatedRouteRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/_authenticated/access-denied': {
      id: '/$lang/_authenticated/access-denied'
      path: '/access-denied'
      fullPath: '/$lang/access-denied'
      preLoaderRoute: typeof LangAuthenticatedAccessDeniedRouteImport
      parentRoute: typeof LangAuthenticatedRouteRoute
    }
    '/$lang/_public/_guest': {
      id: '/$lang/_public/_guest'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangPublicGuestRouteRouteImport
      parentRoute: typeof LangPublicRouteRoute
    }
    '/$lang/_authenticated/workspaces': {
      id: '/$lang/_authenticated/workspaces'
      path: '/workspaces'
      fullPath: '/$lang/workspaces'
      preLoaderRoute: typeof LangAuthenticatedWorkspacesRouteRouteImport
      parentRoute: typeof LangAuthenticatedRouteRoute
    }
    '/$lang/_authenticated/_app': {
      id: '/$lang/_authenticated/_app'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangAuthenticatedAppRouteRouteImport
      parentRoute: typeof LangAuthenticatedRouteRoute
    }
    '/$lang/_authenticated/workspaces/': {
      id: '/$lang/_authenticated/workspaces/'
      path: '/'
      fullPath: '/$lang/workspaces/'
      preLoaderRoute: typeof LangAuthenticatedWorkspacesIndexRouteImport
      parentRoute: typeof LangAuthenticatedWorkspacesRouteRoute
    }
    '/$lang/_authenticated/organizations/': {
      id: '/$lang/_authenticated/organizations/'
      path: '/organizations'
      fullPath: '/$lang/organizations/'
      preLoaderRoute: typeof LangAuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof LangAuthenticatedRouteRoute
    }
    '/$lang/_public/verify-email/$token': {
      id: '/$lang/_public/verify-email/$token'
      path: '/verify-email/$token'
      fullPath: '/$lang/verify-email/$token'
      preLoaderRoute: typeof LangPublicVerifyEmailTokenRouteImport
      parentRoute: typeof LangPublicRouteRoute
    }
    '/$lang/_public/invite/$token': {
      id: '/$lang/_public/invite/$token'
      path: '/invite/$token'
      fullPath: '/$lang/invite/$token'
      preLoaderRoute: typeof LangPublicInviteTokenRouteImport
      parentRoute: typeof LangPublicRouteRoute
    }
    '/$lang/_public/_guest/sign-up': {
      id: '/$lang/_public/_guest/sign-up'
      path: '/sign-up'
      fullPath: '/$lang/sign-up'
      preLoaderRoute: typeof LangPublicGuestSignUpRouteImport
      parentRoute: typeof LangPublicGuestRouteRoute
    }
    '/$lang/_public/_guest/sign-in': {
      id: '/$lang/_public/_guest/sign-in'
      path: '/sign-in'
      fullPath: '/$lang/sign-in'
      preLoaderRoute: typeof LangPublicGuestSignInRouteImport
      parentRoute: typeof LangPublicGuestRouteRoute
    }
    '/$lang/_authenticated/workspaces/new': {
      id: '/$lang/_authenticated/workspaces/new'
      path: '/new'
      fullPath: '/$lang/workspaces/new'
      preLoaderRoute: typeof LangAuthenticatedWorkspacesNewRouteImport
      parentRoute: typeof LangAuthenticatedWorkspacesRouteRoute
    }
    '/$lang/_authenticated/workspace/$workspaceId': {
      id: '/$lang/_authenticated/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/$lang/workspace/$workspaceId'
      preLoaderRoute: typeof LangAuthenticatedWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof LangAuthenticatedRouteRoute
    }
    '/$lang/_authenticated/organizations/new': {
      id: '/$lang/_authenticated/organizations/new'
      path: '/organizations/new'
      fullPath: '/$lang/organizations/new'
      preLoaderRoute: typeof LangAuthenticatedOrganizationsNewRouteImport
      parentRoute: typeof LangAuthenticatedRouteRoute
    }
    '/$lang/_authenticated/organizations/$organizationId': {
      id: '/$lang/_authenticated/organizations/$organizationId'
      path: '/organizations/$organizationId'
      fullPath: '/$lang/organizations/$organizationId'
      preLoaderRoute: typeof LangAuthenticatedOrganizationsOrganizationIdRouteImport
      parentRoute: typeof LangAuthenticatedRouteRoute
    }
    '/$lang/_authenticated/_app/schedule': {
      id: '/$lang/_authenticated/_app/schedule'
      path: '/schedule'
      fullPath: '/$lang/schedule'
      preLoaderRoute: typeof LangAuthenticatedAppScheduleRouteImport
      parentRoute: typeof LangAuthenticatedAppRouteRoute
    }
    '/$lang/_authenticated/_app/my-chat': {
      id: '/$lang/_authenticated/_app/my-chat'
      path: '/my-chat'
      fullPath: '/$lang/my-chat'
      preLoaderRoute: typeof LangAuthenticatedAppMyChatRouteImport
      parentRoute: typeof LangAuthenticatedAppRouteRoute
    }
    '/$lang/_authenticated/_app/colaborando': {
      id: '/$lang/_authenticated/_app/colaborando'
      path: '/colaborando'
      fullPath: '/$lang/colaborando'
      preLoaderRoute: typeof LangAuthenticatedAppColaborandoRouteImport
      parentRoute: typeof LangAuthenticatedAppRouteRoute
    }
    '/$lang/_authenticated/workspaces/$workspaceId': {
      id: '/$lang/_authenticated/workspaces/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/$lang/workspaces/$workspaceId'
      preLoaderRoute: typeof LangAuthenticatedWorkspacesWorkspaceIdRouteRouteImport
      parentRoute: typeof LangAuthenticatedWorkspacesRouteRoute
    }
    '/$lang/_authenticated/_app/page/$pageId': {
      id: '/$lang/_authenticated/_app/page/$pageId'
      path: '/page/$pageId'
      fullPath: '/$lang/page/$pageId'
      preLoaderRoute: typeof LangAuthenticatedAppPagePageIdRouteImport
      parentRoute: typeof LangAuthenticatedAppRouteRoute
    }
    '/$lang/_authenticated/workspaces/$workspaceId/settings': {
      id: '/$lang/_authenticated/workspaces/$workspaceId/settings'
      path: '/settings'
      fullPath: '/$lang/workspaces/$workspaceId/settings'
      preLoaderRoute: typeof LangAuthenticatedWorkspacesWorkspaceIdSettingsRouteRouteImport
      parentRoute: typeof LangAuthenticatedWorkspacesWorkspaceIdRouteRoute
    }
    '/$lang/_authenticated/access/$scope/$scopeId': {
      id: '/$lang/_authenticated/access/$scope/$scopeId'
      path: '/access/$scope/$scopeId'
      fullPath: '/$lang/access/$scope/$scopeId'
      preLoaderRoute: typeof LangAuthenticatedAccessScopeScopeIdRouteRouteImport
      parentRoute: typeof LangAuthenticatedRouteRoute
    }
    '/$lang/_authenticated/workspaces/$workspaceId/settings/': {
      id: '/$lang/_authenticated/workspaces/$workspaceId/settings/'
      path: '/'
      fullPath: '/$lang/workspaces/$workspaceId/settings/'
      preLoaderRoute: typeof LangAuthenticatedWorkspacesWorkspaceIdSettingsIndexRouteImport
      parentRoute: typeof LangAuthenticatedWorkspacesWorkspaceIdSettingsRouteRoute
    }
    '/$lang/_authenticated/access/$scope/$scopeId/': {
      id: '/$lang/_authenticated/access/$scope/$scopeId/'
      path: '/'
      fullPath: '/$lang/access/$scope/$scopeId/'
      preLoaderRoute: typeof LangAuthenticatedAccessScopeScopeIdIndexRouteImport
      parentRoute: typeof LangAuthenticatedAccessScopeScopeIdRouteRoute
    }
    '/$lang/_authenticated/workspaces/$workspaceId/settings/members': {
      id: '/$lang/_authenticated/workspaces/$workspaceId/settings/members'
      path: '/members'
      fullPath: '/$lang/workspaces/$workspaceId/settings/members'
      preLoaderRoute: typeof LangAuthenticatedWorkspacesWorkspaceIdSettingsMembersRouteImport
      parentRoute: typeof LangAuthenticatedWorkspacesWorkspaceIdSettingsRouteRoute
    }
    '/$lang/_authenticated/workspaces/$workspaceId/settings/general': {
      id: '/$lang/_authenticated/workspaces/$workspaceId/settings/general'
      path: '/general'
      fullPath: '/$lang/workspaces/$workspaceId/settings/general'
      preLoaderRoute: typeof LangAuthenticatedWorkspacesWorkspaceIdSettingsGeneralRouteImport
      parentRoute: typeof LangAuthenticatedWorkspacesWorkspaceIdSettingsRouteRoute
    }
    '/$lang/_authenticated/access/$scope/$scopeId/roles': {
      id: '/$lang/_authenticated/access/$scope/$scopeId/roles'
      path: '/roles'
      fullPath: '/$lang/access/$scope/$scopeId/roles'
      preLoaderRoute: typeof LangAuthenticatedAccessScopeScopeIdRolesRouteImport
      parentRoute: typeof LangAuthenticatedAccessScopeScopeIdRouteRoute
    }
    '/$lang/_authenticated/access/$scope/$scopeId/requests/': {
      id: '/$lang/_authenticated/access/$scope/$scopeId/requests/'
      path: '/requests'
      fullPath: '/$lang/access/$scope/$scopeId/requests/'
      preLoaderRoute: typeof LangAuthenticatedAccessScopeScopeIdRequestsIndexRouteImport
      parentRoute: typeof LangAuthenticatedAccessScopeScopeIdRouteRoute
    }
    '/$lang/_authenticated/access/$scope/$scopeId/requests/$requestId': {
      id: '/$lang/_authenticated/access/$scope/$scopeId/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/$lang/access/$scope/$scopeId/requests/$requestId'
      preLoaderRoute: typeof LangAuthenticatedAccessScopeScopeIdRequestsRequestIdRouteImport
      parentRoute: typeof LangAuthenticatedAccessScopeScopeIdRouteRoute
    }
    '/$lang/_authenticated/access/$scope/$scopeId/member/$memberId': {
      id: '/$lang/_authenticated/access/$scope/$scopeId/member/$memberId'
      path: '/member/$memberId'
      fullPath: '/$lang/access/$scope/$scopeId/member/$memberId'
      preLoaderRoute: typeof LangAuthenticatedAccessScopeScopeIdMemberMemberIdRouteImport
      parentRoute: typeof LangAuthenticatedAccessScopeScopeIdRouteRoute
    }
  }
}

interface LangAuthenticatedAppRouteRouteChildren {
  LangAuthenticatedAppColaborandoRoute: typeof LangAuthenticatedAppColaborandoRoute
  LangAuthenticatedAppMyChatRoute: typeof LangAuthenticatedAppMyChatRoute
  LangAuthenticatedAppScheduleRoute: typeof LangAuthenticatedAppScheduleRoute
  LangAuthenticatedAppPagePageIdRoute: typeof LangAuthenticatedAppPagePageIdRoute
}

const LangAuthenticatedAppRouteRouteChildren: LangAuthenticatedAppRouteRouteChildren =
  {
    LangAuthenticatedAppColaborandoRoute: LangAuthenticatedAppColaborandoRoute,
    LangAuthenticatedAppMyChatRoute: LangAuthenticatedAppMyChatRoute,
    LangAuthenticatedAppScheduleRoute: LangAuthenticatedAppScheduleRoute,
    LangAuthenticatedAppPagePageIdRoute: LangAuthenticatedAppPagePageIdRoute,
  }

const LangAuthenticatedAppRouteRouteWithChildren =
  LangAuthenticatedAppRouteRoute._addFileChildren(
    LangAuthenticatedAppRouteRouteChildren,
  )

interface LangAuthenticatedWorkspacesWorkspaceIdSettingsRouteRouteChildren {
  LangAuthenticatedWorkspacesWorkspaceIdSettingsGeneralRoute: typeof LangAuthenticatedWorkspacesWorkspaceIdSettingsGeneralRoute
  LangAuthenticatedWorkspacesWorkspaceIdSettingsMembersRoute: typeof LangAuthenticatedWorkspacesWorkspaceIdSettingsMembersRoute
  LangAuthenticatedWorkspacesWorkspaceIdSettingsIndexRoute: typeof LangAuthenticatedWorkspacesWorkspaceIdSettingsIndexRoute
}

const LangAuthenticatedWorkspacesWorkspaceIdSettingsRouteRouteChildren: LangAuthenticatedWorkspacesWorkspaceIdSettingsRouteRouteChildren =
  {
    LangAuthenticatedWorkspacesWorkspaceIdSettingsGeneralRoute:
      LangAuthenticatedWorkspacesWorkspaceIdSettingsGeneralRoute,
    LangAuthenticatedWorkspacesWorkspaceIdSettingsMembersRoute:
      LangAuthenticatedWorkspacesWorkspaceIdSettingsMembersRoute,
    LangAuthenticatedWorkspacesWorkspaceIdSettingsIndexRoute:
      LangAuthenticatedWorkspacesWorkspaceIdSettingsIndexRoute,
  }

const LangAuthenticatedWorkspacesWorkspaceIdSettingsRouteRouteWithChildren =
  LangAuthenticatedWorkspacesWorkspaceIdSettingsRouteRoute._addFileChildren(
    LangAuthenticatedWorkspacesWorkspaceIdSettingsRouteRouteChildren,
  )

interface LangAuthenticatedWorkspacesWorkspaceIdRouteRouteChildren {
  LangAuthenticatedWorkspacesWorkspaceIdSettingsRouteRoute: typeof LangAuthenticatedWorkspacesWorkspaceIdSettingsRouteRouteWithChildren
}

const LangAuthenticatedWorkspacesWorkspaceIdRouteRouteChildren: LangAuthenticatedWorkspacesWorkspaceIdRouteRouteChildren =
  {
    LangAuthenticatedWorkspacesWorkspaceIdSettingsRouteRoute:
      LangAuthenticatedWorkspacesWorkspaceIdSettingsRouteRouteWithChildren,
  }

const LangAuthenticatedWorkspacesWorkspaceIdRouteRouteWithChildren =
  LangAuthenticatedWorkspacesWorkspaceIdRouteRoute._addFileChildren(
    LangAuthenticatedWorkspacesWorkspaceIdRouteRouteChildren,
  )

interface LangAuthenticatedWorkspacesRouteRouteChildren {
  LangAuthenticatedWorkspacesWorkspaceIdRouteRoute: typeof LangAuthenticatedWorkspacesWorkspaceIdRouteRouteWithChildren
  LangAuthenticatedWorkspacesNewRoute: typeof LangAuthenticatedWorkspacesNewRoute
  LangAuthenticatedWorkspacesIndexRoute: typeof LangAuthenticatedWorkspacesIndexRoute
}

const LangAuthenticatedWorkspacesRouteRouteChildren: LangAuthenticatedWorkspacesRouteRouteChildren =
  {
    LangAuthenticatedWorkspacesWorkspaceIdRouteRoute:
      LangAuthenticatedWorkspacesWorkspaceIdRouteRouteWithChildren,
    LangAuthenticatedWorkspacesNewRoute: LangAuthenticatedWorkspacesNewRoute,
    LangAuthenticatedWorkspacesIndexRoute:
      LangAuthenticatedWorkspacesIndexRoute,
  }

const LangAuthenticatedWorkspacesRouteRouteWithChildren =
  LangAuthenticatedWorkspacesRouteRoute._addFileChildren(
    LangAuthenticatedWorkspacesRouteRouteChildren,
  )

interface LangAuthenticatedAccessScopeScopeIdRouteRouteChildren {
  LangAuthenticatedAccessScopeScopeIdRolesRoute: typeof LangAuthenticatedAccessScopeScopeIdRolesRoute
  LangAuthenticatedAccessScopeScopeIdIndexRoute: typeof LangAuthenticatedAccessScopeScopeIdIndexRoute
  LangAuthenticatedAccessScopeScopeIdMemberMemberIdRoute: typeof LangAuthenticatedAccessScopeScopeIdMemberMemberIdRoute
  LangAuthenticatedAccessScopeScopeIdRequestsRequestIdRoute: typeof LangAuthenticatedAccessScopeScopeIdRequestsRequestIdRoute
  LangAuthenticatedAccessScopeScopeIdRequestsIndexRoute: typeof LangAuthenticatedAccessScopeScopeIdRequestsIndexRoute
}

const LangAuthenticatedAccessScopeScopeIdRouteRouteChildren: LangAuthenticatedAccessScopeScopeIdRouteRouteChildren =
  {
    LangAuthenticatedAccessScopeScopeIdRolesRoute:
      LangAuthenticatedAccessScopeScopeIdRolesRoute,
    LangAuthenticatedAccessScopeScopeIdIndexRoute:
      LangAuthenticatedAccessScopeScopeIdIndexRoute,
    LangAuthenticatedAccessScopeScopeIdMemberMemberIdRoute:
      LangAuthenticatedAccessScopeScopeIdMemberMemberIdRoute,
    LangAuthenticatedAccessScopeScopeIdRequestsRequestIdRoute:
      LangAuthenticatedAccessScopeScopeIdRequestsRequestIdRoute,
    LangAuthenticatedAccessScopeScopeIdRequestsIndexRoute:
      LangAuthenticatedAccessScopeScopeIdRequestsIndexRoute,
  }

const LangAuthenticatedAccessScopeScopeIdRouteRouteWithChildren =
  LangAuthenticatedAccessScopeScopeIdRouteRoute._addFileChildren(
    LangAuthenticatedAccessScopeScopeIdRouteRouteChildren,
  )

interface LangAuthenticatedRouteRouteChildren {
  LangAuthenticatedAppRouteRoute: typeof LangAuthenticatedAppRouteRouteWithChildren
  LangAuthenticatedWorkspacesRouteRoute: typeof LangAuthenticatedWorkspacesRouteRouteWithChildren
  LangAuthenticatedAccessDeniedRoute: typeof LangAuthenticatedAccessDeniedRoute
  LangAuthenticatedOrganizationsOrganizationIdRoute: typeof LangAuthenticatedOrganizationsOrganizationIdRoute
  LangAuthenticatedOrganizationsNewRoute: typeof LangAuthenticatedOrganizationsNewRoute
  LangAuthenticatedWorkspaceWorkspaceIdRoute: typeof LangAuthenticatedWorkspaceWorkspaceIdRoute
  LangAuthenticatedOrganizationsIndexRoute: typeof LangAuthenticatedOrganizationsIndexRoute
  LangAuthenticatedAccessScopeScopeIdRouteRoute: typeof LangAuthenticatedAccessScopeScopeIdRouteRouteWithChildren
}

const LangAuthenticatedRouteRouteChildren: LangAuthenticatedRouteRouteChildren =
  {
    LangAuthenticatedAppRouteRoute: LangAuthenticatedAppRouteRouteWithChildren,
    LangAuthenticatedWorkspacesRouteRoute:
      LangAuthenticatedWorkspacesRouteRouteWithChildren,
    LangAuthenticatedAccessDeniedRoute: LangAuthenticatedAccessDeniedRoute,
    LangAuthenticatedOrganizationsOrganizationIdRoute:
      LangAuthenticatedOrganizationsOrganizationIdRoute,
    LangAuthenticatedOrganizationsNewRoute:
      LangAuthenticatedOrganizationsNewRoute,
    LangAuthenticatedWorkspaceWorkspaceIdRoute:
      LangAuthenticatedWorkspaceWorkspaceIdRoute,
    LangAuthenticatedOrganizationsIndexRoute:
      LangAuthenticatedOrganizationsIndexRoute,
    LangAuthenticatedAccessScopeScopeIdRouteRoute:
      LangAuthenticatedAccessScopeScopeIdRouteRouteWithChildren,
  }

const LangAuthenticatedRouteRouteWithChildren =
  LangAuthenticatedRouteRoute._addFileChildren(
    LangAuthenticatedRouteRouteChildren,
  )

interface LangPublicGuestRouteRouteChildren {
  LangPublicGuestSignInRoute: typeof LangPublicGuestSignInRoute
  LangPublicGuestSignUpRoute: typeof LangPublicGuestSignUpRoute
}

const LangPublicGuestRouteRouteChildren: LangPublicGuestRouteRouteChildren = {
  LangPublicGuestSignInRoute: LangPublicGuestSignInRoute,
  LangPublicGuestSignUpRoute: LangPublicGuestSignUpRoute,
}

const LangPublicGuestRouteRouteWithChildren =
  LangPublicGuestRouteRoute._addFileChildren(LangPublicGuestRouteRouteChildren)

interface LangPublicRouteRouteChildren {
  LangPublicGuestRouteRoute: typeof LangPublicGuestRouteRouteWithChildren
  LangPublicInviteTokenRoute: typeof LangPublicInviteTokenRoute
  LangPublicVerifyEmailTokenRoute: typeof LangPublicVerifyEmailTokenRoute
}

const LangPublicRouteRouteChildren: LangPublicRouteRouteChildren = {
  LangPublicGuestRouteRoute: LangPublicGuestRouteRouteWithChildren,
  LangPublicInviteTokenRoute: LangPublicInviteTokenRoute,
  LangPublicVerifyEmailTokenRoute: LangPublicVerifyEmailTokenRoute,
}

const LangPublicRouteRouteWithChildren = LangPublicRouteRoute._addFileChildren(
  LangPublicRouteRouteChildren,
)

interface LangRouteRouteChildren {
  LangAuthenticatedRouteRoute: typeof LangAuthenticatedRouteRouteWithChildren
  LangPublicRouteRoute: typeof LangPublicRouteRouteWithChildren
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangAuthenticatedRouteRoute: LangAuthenticatedRouteRouteWithChildren,
  LangPublicRouteRoute: LangPublicRouteRouteWithChildren,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
